config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/TC-GNN:
      branch: main
      repo: https://github.com/HPCI-Lab/TC-GNN
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/TC-GNN git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-pumpkin-wallaby.sh
        container: qc.acc_chummy-tan-mist
  QC.Doc:
    repos:
      github.com/HPCI-Lab/TC-GNN find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-charcoal-koala.sh
        container: qc.doc_tacky-rust-spaniel
      github.com/HPCI-Lab/TC-GNN git:
        commands:
        - /usr/bin/env sh .sqa/script.surly-maroon-panda.sh
        container: qc.doc_pretty-xanthic-barb
  QC.Lic:
    repos:
      github.com/HPCI-Lab/TC-GNN licensee:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-ruby-loon.sh
        container: qc.lic_breezy-charcoal-dingo
  QC.Ver:
    repos:
      github.com/HPCI-Lab/TC-GNN get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-chartreuse-cheetah.sh
        container: qc.ver_bluesy-sepia-wombat
timeout: 5400
